POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZyZHJpY2siLCJpZCI6IjY5OTg1NjliMmM4NWQwNjMzYTE3OGY0MyIsImlhdCI6MTc3MTU5MzcxMn0.pJQiD4WzUptOsoBcS5ElM9tEQJ7rUQwqBkah0t9e88Q

{
  "title": "Onyis SecondThings thing",
  "author": "Fedrick",
  "url": "fouth url",
  "likes": "4983",
  "userId": "69985520e20beb11b30e2a8e"
}