POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Onyis fourihfdshjfweth thing",
  "author": "Fedrick",
  "url": "fouth url",
  "likes": "4983",
  "userId": "69985520e20beb11b30e2a8e"
}